[package]
name = "ssr-facade"
description = "implementation of ssr-core TasksFacade trait"
version = "0.2.0"
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
ssr-core = "0.19.0"
