[package]
name = "ssr-facade"
description = "implementation of ssr-core TasksFacade trait"
version = "0.5.1"
license = "MIT"
edition = "2021"

[dependencies]
s_text_input_f = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
ssr-core = "0.27"
