[package]
name = "ssr-facade"
description = "implementation of ssr-core TasksFacade trait"
version = "0.4.0"
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssr-core = "0.25.1"
